# Generated by Django 6.1.1 on 2026-09-21 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_attributes_product_branch_product_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='allocated_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='new_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='previous_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
