# Generated by Django 6.1.1 on 2026-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_inventory_allocated_qty_inventory_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
