# Generated by Django 6.1.1 on 2026-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
