# Generated by Django 6.1.1 on 2026-09-30 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_last_posted_at'),
        ('shops', '0019_shop_payout_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BStockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_transfers_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_transfers_out', to='shops.branch')),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_transfers_out', to='shops.shop')),
                ('to_branch', models.ForeignKey(blank=True, help_text='Optional; the buyer defaults to their main (or first) branch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2b_transfers_in', to='shops.branch')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_transfers_in', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BStockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='pcs', max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_transfer_items_sent', to='products.product')),
                ('received_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_transfer_items_received', to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.b2bstocktransfer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='b2bstocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_shop', models.F('to_shop')), _negated=True), name='b2b_transfer_shops_differ'),
        ),
    ]
