# Generated by Django 6.1.1 on 2026-09-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_b2bstocktransfer_b2bstocktransferitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bstocktransferitem',
            name='mapped_product',
            field=models.ForeignKey(blank=True, help_text='Buyer-side choice: the receiving product this line lands on at completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_transfer_items_mapped', to='products.product'),
        ),
    ]
