# Generated by Django 6.1.1 on 2026-10-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_b2bstocktransferitem_mapped_product'),
        ('sales', '0011_alter_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bstocktransfer',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Set when the manifest was staged automatically from a POS sale; stock was already deducted by that sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_delivery_manifests', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='b2bstocktransfer',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual dispatch'), ('sale', 'Point-of-sale delivery')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='b2bstocktransferitem',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
