# Generated by Django 6.1.1 on 2026-10-01

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower


def merge_case_variant_categories(apps, schema_editor):
    """Collapse per-shop categories whose names differ only by case or padding.

    Keeps the oldest row of each (shop, lower(stripped name)) group, re-points
    its products, then deletes the duplicate shells — no product data is lost.
    Runs before the case-insensitive constraint so existing rows can't block it.
    """
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    keepers = {}
    duplicates = {}
    for category in Category.objects.order_by('created_at', 'id').iterator():
        key = (category.shop_id, (category.name or '').strip().lower())
        if key in keepers:
            duplicates[category.pk] = keepers[key].pk
        else:
            keepers[key] = category
    for duplicate_pk, keeper_pk in duplicates.items():
        Product.objects.filter(category_id=duplicate_pk).update(category_id=keeper_pk)
    Category.objects.filter(pk__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_sale_delivery_manifests'),
    ]

    operations = [
        migrations.RunPython(merge_case_variant_categories, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint('shop', Lower('name'), name='uniq_category_shop_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='merchantcategory',
            constraint=models.UniqueConstraint(fields=['shop', 'parent', 'name'], name='uniq_merchantcat_shop_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='merchantcategory',
            constraint=models.UniqueConstraint(fields=['shop', 'name'], condition=Q(parent__isnull=True), name='uniq_merchantcat_root_name'),
        ),
    ]
