# Generated by Django 6.1.1 on 2026-09-30 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_product_last_posted_at'),
        ('shops', '0019_shop_payout_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('applied', 'Applied')], db_index=True, default='pending', max_length=20)),
                ('source_type', models.CharField(choices=[('qr', 'QR code'), ('image', 'Image'), ('url', 'Media URL')], default='image', max_length=20)),
                ('engine_used', models.CharField(blank=True, choices=[('qr', 'QR'), ('ai', 'AI vision')], default='', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('source_note', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('item_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_batches', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_batches', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_sw', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='pcs', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category_name', models.CharField(blank=True, default='', max_length=255)),
                ('ai_confidence_score', models.FloatField(default=0.0)),
                ('tra_item_code', models.CharField(blank=True, default='', max_length=20)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('applied_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_drafts', to='products.product')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='intake.intakebatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
