# Generated by Django 6.1.1 on 2026-10-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakebatch',
            name='ai_usage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
