# Generated by Django 6.1.1 on 2026-09-28 19:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_approval_status_order_customer_name_and_more'),
        ('shops', '0011_alter_userrole_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_by_name', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_by_name', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expected_closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_left_for_next_day', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_submitted_to_owner', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner_approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=50)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_opened', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.shift'),
        ),
    ]
