# Generated by Django 6.1.1 on 2026-09-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_shift_sale_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-opened_at']},
        ),
    ]
