# Generated by Django 6.1.1 on 2026-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_order_customer_user_order_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('awaiting_shipment', 'Awaiting Shipment'), ('confirmed', 'Confirmed'), ('allocated', 'Allocated'), ('picking', 'Picking'), ('packed', 'Packed'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
