# Generated by Django 6.1.1 on 2026-09-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_order_paid_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
