# Generated by Django 6.1.1 on 2026-09-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('public_storefront', 'Public Storefront'), ('in_app', 'In App'), ('wishlist', 'Wishlist')], default='in_app', max_length=50),
        ),
    ]
