# Generated by Django 6.1.1 on 2026-09-29 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Alert')], default='info', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_by_email', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('shop_id', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField()),
                ('category', models.CharField(default='Bug', max_length=50)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
