# Generated by Django 6.1.1 on 2026-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_branch_branch_type_branch_features_branch_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='online_store_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='store_policies',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
