# Generated by Django 6.1.1 on 2026-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_online_store_settings_shop_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ai_marketing_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
