# Generated by Django 6.1.1 on 2026-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_ai_marketing_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
