# Generated by Django 6.1.1 on 2026-09-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shop_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='coverImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='imageUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='isWholesaleSupplier',
            field=models.BooleanField(default=False),
        ),
    ]
