# Generated by Django 6.1.1 on 2026-09-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-created_at']},
        ),
    ]
