# Generated by Django 6.1.1 on 2026-09-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_alter_userrole_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
    ]
