# Generated by Django 6.1.1 on 2026-09-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_shop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at']},
        ),
    ]
