# Generated by Django 6.1.1 on 2026-09-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_alter_invitation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
