# Generated by Django 6.1.1 on 2026-09-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_shop_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='coverImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='imageUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
