# Generated by Django 6.1.1 on 2026-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_alter_shop_coverimage_alter_shop_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
