# Generated by Django 6.1.1 on 2026-09-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_branch_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='setupProgress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='setupStatus',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='verificationStatus',
            field=models.CharField(default='unverified', max_length=20),
        ),
    ]
