# Generated by Django 6.1.1 on 2026-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_shop_setupprogress_shop_setupstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='payout_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
