# Generated by Django 6.1.1 on 2026-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ai_intake_monthly_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
