# Generated by Django 6.1.1 on 2026-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('merchant', 'Merchant'), ('staff', 'Staff'), ('customer', 'Customer'), ('unassigned', 'Unassigned')], default='merchant', max_length=20),
        ),
    ]
