# Generated by Django 6.1.1 on 2026-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_workspace',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
