# Generated by Django 6.1.1 on 2026-09-29 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_default_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=64)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('confirmed_by', models.CharField(blank=True, default='', max_length=128)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='business_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shop_id', models.CharField(blank=True, default='', max_length=128)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product_id')},
            },
        ),
    ]
