"""
Django settings for twende_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
import secrets
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in production. In DEBUG mode a random ephemeral key is
# generated so local dev works without configuration (sessions reset on restart).
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() in ('true', '1', 'yes')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False.')

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]

# OAuth client used to verify Google Identity Services ID tokens. Empty means
# Google sign-in is not offered by this deployment (email/password still works).
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '').strip()

# Firebase project whose ID tokens the bridge endpoint trusts (frontend project).
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', 'duka-smart-16c8e')

# Service account used by `manage.py import_firestore` to backfill live data.
# The key is not kept in the repository; point FIREBASE_CREDENTIALS at the file
# (or paste its JSON) wherever it is stored outside the workspace.
FIREBASE_CREDENTIALS = os.environ.get(
    'FIREBASE_CREDENTIALS', str(BASE_DIR / 'firebase-key.json')
)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Registers the trigram lookup (``trigram_word_similar``) used by
    # apps/core/search.py for typo-tolerant candidates on PostgreSQL.
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'apps.users',
    'apps.shops',
    'apps.products',
    'apps.sales',
    'apps.expenses',
    'apps.crm',
    'apps.core',
    'apps.purchases',
    'apps.marketing',
    'apps.social',
    'apps.telemetry',
    'apps.corporate',
    'apps.intake',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT (compressed) and silences 404 noise for missing assets.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# SQLite for local dev; Postgres when POSTGRES_DB is set (matches the `db`
# service in docker-compose.yml / docker-compose.prod.yml).
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'db'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            # Persistent connections + a liveness probe before reuse keep
            # request latency flat; Django drops connections idle for longer
            # than CONN_MAX_AGE seconds.
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# The default PBKDF2 rounds make each create_user() call take ~1.5s, which
# turns the API suite into an ordeal. Hashes only ever matter at login.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Celery
# Runs the ported Cloud Functions (marketing drips, social scheduler, AI
# insights). Defaults point at a local Redis; set CELERY_TASK_ALWAYS_EAGER=true
# to run tasks inline (used by the test suite).

from celery.schedules import crontab  # noqa: E402  (kept next to its usage)

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND') or None
# The test suite runs tasks inline so it never needs a live broker.
CELERY_TASK_ALWAYS_EAGER = (
    os.environ.get('CELERY_TASK_ALWAYS_EAGER', '').strip().lower() in ('true', '1', 'yes')
    or 'test' in sys.argv
)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
# Beat persists its shelve schedule into CWD by default, which is unwritable in
# the image (runs as uid 1000, /app is root-owned). The state is reconstructible
# from CELERY_BEAT_SCHEDULE, so a world-writable temp dir is fine.
CELERY_BEAT_SCHEDULE_FILENAME = os.environ.get(
    'CELERY_BEAT_SCHEDULE_FILENAME', '/tmp/celerybeat-schedule'
)
# Entries are registered by the scheduler ports (social/marketing drips).
CELERY_BEAT_SCHEDULE = {
    # Port of the legacy `dailySocialScheduler` Cloud Function.
    'daily-social-poster': {
        'task': 'apps.social.tasks.daily_social_poster',
        'schedule': crontab(hour=10, minute=0),
        'options': {'timezone': 'Africa/Nairobi'},
    },
    # Port of the legacy `peakHoursMarketingDrip` Cloud Function.
    'peak-hours-marketing-drip': {
        'task': 'apps.social.tasks.peak_hours_marketing_drip',
        'schedule': crontab(hour='7,12,19', minute=30),
        'options': {'timezone': 'Africa/Dar_es_Salaam'},
    },
}


# Facebook Login (social domain)
# Credentials of the Facebook app used by the frontend dialog. The redirect URI
# must be registered on that app; the default is the legacy Cloud Functions URL
# so existing deployments keep working until the callback is switched over.

FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET', '')
FACEBOOK_REDIRECT_URI = os.environ.get(
    'FACEBOOK_REDIRECT_URI',
    'https://us-central1-duka-smart-16c8e.cloudfunctions.net/facebookCallback',
)
FACEBOOK_GRAPH_BASE_URL = os.environ.get('FACEBOOK_GRAPH_BASE_URL', 'https://graph.facebook.com')
FACEBOOK_GRAPH_VERSION = os.environ.get('FACEBOOK_GRAPH_VERSION', 'v18.0')
# Extra origins allowed to receive the OAuth redirect back from the callback.
# The production origin is always allowed; localhost is allowed implicitly.
FACEBOOK_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('FACEBOOK_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
# Webhook (Facebook -> Django). The GET handshake token defaults to the legacy
# Cloud Function literal so an existing subscription keeps working after the
# callback URL is pointed at this deployment.
FACEBOOK_WEBHOOK_VERIFY_TOKEN = os.environ.get(
    'FACEBOOK_WEBHOOK_VERIFY_TOKEN', 'biashara-connect-webhook-secret-2024'
)
# Signature checking is skipped while FACEBOOK_APP_SECRET is empty (legacy
# parity, dev); once the secret is configured the POST body must carry a valid
# X-Hub-Signature-256. Set to false only to keep accepting unsigned events.
FACEBOOK_WEBHOOK_VERIFY_SIGNATURE = os.environ.get(
    'FACEBOOK_WEBHOOK_VERIFY_SIGNATURE', 'true'
).strip().lower() not in ('false', '0', 'no')

# Passphrase for the crypto-js token envelope (apps.core.crypto). ENCRYPTION_KEY
# is the variable the Cloud Functions used; SOCIAL_TOKEN_ENCRYPTION_KEY lets the
# Django side rotate independently later.
SOCIAL_TOKEN_ENCRYPTION_KEY = (
    os.environ.get('SOCIAL_TOKEN_ENCRYPTION_KEY')
    or os.environ.get('ENCRYPTION_KEY')
    or ''
)

# Social posting (apps.social.posting / apps.social.reels)
# Reels are fetched by Facebook over the public internet, so the generator
# refuses to run unless REEL_PUBLIC_BASE_URL points at this deployment (the
# poster then degrades to an image post, like the Cloud Function did on any
# ffmpeg/upload failure). Media is served by Django in dev only.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
REEL_PUBLIC_BASE_URL = os.environ.get('REEL_PUBLIC_BASE_URL', '')

# Captions come from OpenRouter (the provider the Cloud Function used). With no
# key configured the poster skips the AI step and uses the product/price text.
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')

# Product intake (apps.intake.ai_extract): the cheap vision model runs first
# and its answer is kept whenever it is confident; only a weak first pass
# pays for one escalation to the strong model.
AI_INTAKE_MODEL = os.environ.get('AI_INTAKE_MODEL', 'google/gemini-2.5-flash')
AI_INTAKE_MODEL_STRONG = os.environ.get('AI_INTAKE_MODEL_STRONG', 'google/gemini-2.5-pro')
AI_INTAKE_MIN_CONFIDENCE = float(os.environ.get('AI_INTAKE_MIN_CONFIDENCE', '0.6'))

# Delivery App sync (apps.core.delivery_sync)
# Port of functions/src/sync/deliverySync.js: mirrors published products into a
# *second* Firebase project (the courier marketplace). Remote writes leave this
# deployment, so the sync is opt-in: with the flag off (the default) every push
# raises and no external call is made.
DELIVERY_APP_SYNC_ENABLED = os.environ.get(
    'DELIVERY_APP_SYNC_ENABLED', ''
).strip().lower() in ('true', '1', 'yes')
# Service account of the Delivery App project. Not kept in the repository; the
# legacy default path is only a placeholder, set DELIVERY_APP_CREDENTIALS to the
# real file to use the sync.
DELIVERY_APP_CREDENTIALS = os.environ.get(
    'DELIVERY_APP_CREDENTIALS', str(BASE_DIR / 'delivery-app-key.json')
)
DELIVERY_APP_PROJECT_ID = os.environ.get('DELIVERY_APP_PROJECT_ID', 'fast-tz')
DELIVERY_APP_COLLECTION = os.environ.get('DELIVERY_APP_COLLECTION', 'products')
DELIVERY_APP_BATCH_SIZE = int(os.environ.get('DELIVERY_APP_BATCH_SIZE', '400'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))

if DEBUG:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
else:
    # WhiteNoise serves STATIC_ROOT with on-the-fly compression and long-lived
    # cache headers. Plain CompressedStaticFilesStorage (not the Manifest
    # variant) so a stale template reference degrades to a 404, not a 500.
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
    }


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'apps.core.pagination.StandardPagination',
    'PAGE_SIZE': 50,
}

# Spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Biashara Connect API',
    'DESCRIPTION': 'B2B and B2C Commerce API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173'
    ).split(',')
    if o.strip()
]
if DEBUG:
    # The vite dev server shifts ports when the default one is taken.
    CORS_ALLOWED_ORIGIN_REGEXES = [r'^http://(localhost|127\.0\.0\.1)(:\d+)?$']
CORS_ALLOW_CREDENTIALS = True

# CSRF origins for the admin and any cookie-authed posts over TLS. Traefik
# terminates HTTPS, so Django sees the request as http:// — the origin list
# must carry the public scheme.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if o.strip()
]

if not DEBUG:
    # Behind Traefik, which sets X-Forwarded-Proto per request.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get(
        'SECURE_SSL_REDIRECT', 'false'
    ).strip().lower() in ('true', '1', 'yes')
    SECURE_REDIRECT_EXEMPT = [r'^healthz/$']
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Opt-in Redis cache. Only honoured when REDIS_CACHE_URL is set explicitly so
# a local CELERY_BROKER_URL default (host port 6379) can never quietly point
# the cache at a foreign Redis instance.
REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', '')
if REDIS_CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_CACHE_URL,
        }
    }

# Simple JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
