# Generated by Django 6.1.1 on 2026-09-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_supplierinvoice_supplierpayment_and_more'),
        ('purchases', '0001_initial'),
        ('shops', '0004_branch_branch_type_branch_features_branch_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.supplier'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='payments', to='crm.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.supplier'),
        ),
    ]
