# Generated by Django 6.1.1 on 2026-09-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_supplierinvoice_purchase_order_supplierinvoice_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='platform_shop_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
