# Generated by Django 6.1.1 on 2026-09-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_supplier_notes_supplier_owner_id_supplier_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierinvoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-created_at']},
        ),
    ]
