# Generated by Django 6.1.1 on 2026-09-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
