# Generated by Django 6.1.1 on 2026-09-30 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporatePurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.CharField(db_index=True, max_length=128)),
                ('shop_id', models.CharField(blank=True, default='', max_length=128)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('buyer_id', models.CharField(blank=True, default='', max_length=128)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255)),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('department_id', models.CharField(blank=True, default='', max_length=128)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('items', models.JSONField(blank=True, default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approval_status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='pending_approval', max_length=20)),
                ('approver_id', models.CharField(blank=True, default='', max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
