# Generated by Django 6.1.1 on 2026-09-21 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='TZS', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='timeline',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='source_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='dispatch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='supplier_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='timeline',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseshipment',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='preparing', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=255)),
                ('source_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('shipped_qty', models.IntegerField(default=0)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseshipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
