# Generated by Django 6.1.1 on 2026-09-30 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_currency_purchaseorder_payment_terms_and_more'),
        ('shops', '0019_shop_payout_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='B2BSupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn_ids', models.JSONField(blank=True, default=list)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('buyer_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_supplier_invoices', to='shops.shop')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_invoices', to='purchases.purchaseorder')),
                ('supplier_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_buyer_invoices', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B2BSupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mobile Money', 'Mobile Money')], default='Cash', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_ids', models.JSONField(blank=True, default=list)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('buyer_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_supplier_payments', to='shops.shop')),
                ('supplier_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_buyer_payments', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B2BConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], max_length=10, null=True)),
                ('credit_days', models.IntegerField(blank=True, null=True)),
                ('pricing_tier', models.CharField(blank=True, choices=[('wholesale', 'Wholesale'), ('corporate', 'Corporate'), ('reseller', 'Reseller')], max_length=20, null=True)),
                ('buyer_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_connections_as_buyer', to='shops.shop')),
                ('supplier_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_connections_as_supplier', to='shops.shop')),
            ],
            options={
                'unique_together': {('buyer_shop', 'supplier_shop')},
            },
        ),
        migrations.CreateModel(
            name='B2BSupplierBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_purchases', models.IntegerField(default=0)),
                ('received_goods_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buyer_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_supplier_balances', to='shops.shop')),
                ('supplier_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_buyer_balances', to='shops.shop')),
            ],
            options={
                'unique_together': {('buyer_shop', 'supplier_shop')},
            },
        ),
    ]
