# Generated by Django 6.1.1 on 2026-09-29 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('shop_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('action', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('shop_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_id', models.CharField(blank=True, default='', max_length=128)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('query', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('is_ai_mode', models.BooleanField(blank=True, null=True)),
                ('context', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('shop_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('action', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('route', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
