# Generated by Django 6.1.1 on 2026-09-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_branch_legacy_id'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegration',
            name='connected_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='socialintegration',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialintegration',
            name='platform',
            field=models.CharField(choices=[('meta', 'Meta/Facebook'), ('facebook', 'Facebook Page'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20),
        ),
        migrations.CreateModel(
            name='FacebookOAuthSession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_token', models.TextField()),
                ('pages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_oauth_sessions', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
