# Generated by Django 6.1.1 on 2026-09-29 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_branch_legacy_id'),
        ('social', '0002_socialintegration_connected_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('social_post', 'Social Post'), ('ai_reply', 'AI Reply')], default='social_post', max_length=20)),
                ('action', models.CharField(choices=[('post', 'Post'), ('reply', 'Reply')], default='post', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('facebook_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('video_fallback_reason', models.TextField(blank=True, null=True)),
                ('instagram_error', models.TextField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_logs', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
