# Generated by Django 6.1.1 on 2026-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_shop_ai_intake_monthly_limit'),
        ('social', '0003_sociallog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.AlterUniqueTogether(
            name='socialintegration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='socialintegration',
            name='page_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sociallog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='socialmsg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallog',
            index=models.Index(fields=['-created_at'], name='sociallog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallog',
            index=models.Index(fields=['status', '-created_at'], name='sociallog_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallog',
            index=models.Index(fields=['shop', '-created_at'], name='sociallog_shop_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialintegration',
            constraint=models.UniqueConstraint(fields=('shop', 'platform'), name='socialint_shop_platform_uniq'),
        ),
    ]
