# Generated by Django 6.1.1 on 2026-10-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallog',
            name='tiktok_publish_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
